version: "3"

services:

  nginx-dev:
    build: nginx/
    container_name: dev-nginx
    volumes:
      - ./config:/config:ro
      - ${PROJECT_PATH}:/www/:rw
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf/nginx/conf.d/:/etc/nginx/conf.d/:rw
      - ./logs/nginx/:/var/log/nginx/:rw
    environment:
      - PROJECT_DOMAIN=${PROJECT_DOMAIN}
    ports:
      - "80:80"
    networks:
      - dev-network
    depends_on:
      - php-56
      - php-70
      - php-71
      - php-72

  mariadb-dev:
    image: mariadb:latest
    container_name: dev-database
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_PWD}
    volumes:
      - ./database/:/var/lib/mysql/:rw
      - ./conf/mariadb/my.cnf:/etc/mysql/my.cnf:ro
      - ./logs/mariadb/:/var/log/mysql:rw
    ports:
      - "3306"
    networks:
      - dev-network

  php-56:
    build: php/56/
    container_name: dev-php-56
    volumes:
      - ${PROJECT_PATH}:/www/:rw
    networks:
      - dev-network

  php-70:
    build: php/70/
    container_name: dev-php-70
    volumes:
      - ${PROJECT_PATH}:/www/:rw
    networks:
      - dev-network

  php-71:
    build: php/71/
    container_name: dev-php-71
    volumes:
      - ${PROJECT_PATH}:/www/:rw
    networks:
      - dev-network

  php-72:
    build: php/72/
    container_name: dev-php-72
    volumes:
      - ${PROJECT_PATH}:/www/:rw
    networks:
      - dev-network

networks: 
  dev-network:
    driver: bridge