version: "3"
services:

  nginx:
    image: nginx:alpine
    container_name: dev-nginx
    volumes:
      - ./www/:/www/:rw
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf/nginx/conf.d/:/etc/nginx/conf.d/:ro
      - ./logs/nginx/:/var/log/nginx/:rw
    ports:
      - "80:80"
    networks:
      - dev-network

  mariadb:
    image: mariadb:latest
    container_name: dev-database
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_PWD}
    volumes:
      - ./database/:/var/lib/mysql/:rw
      - ./conf/mariadb/:/etc/mysql/conf.d/:ro
      - ./logs/mariadb/:/var/log/mariadb:rw
    ports:
      - "3306"
    networks:
      - dev-network

  php:
    build: docker/php/
    container_name: dev-php
    volumes:
      - ./www/:/www/:rw
    networks:
      - dev-network

networks: 
  dev-network:
    driver: bridge